"""empty message

Revision ID: f40517035dfe
Revises: 2807edd385a2
Create Date: 2022-03-13 10:01:45.809807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40517035dfe'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner', sa.Text(), nullable=False),
    sa.Column('banenrUser', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['banenrUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('channel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biography', sa.String(length=10000), nullable=True),
    sa.Column('socialNetwork', sa.String(length=150), nullable=True),
    sa.Column('userChannel', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userChannel'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('following',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('followUser', sa.String(length=50), nullable=False),
    sa.Column('userFollowing', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userFollowing'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.Text(), nullable=False),
    sa.Column('imgUser', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['imgUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userOrig', sa.String(length=40), nullable=False),
    sa.Column('messages', sa.String(length=500), nullable=False),
    sa.Column('userMessages', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userMessages'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movie', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('catMov', sa.Text(), nullable=True),
    sa.Column('sizeVideo', sa.Integer(), nullable=True),
    sa.Column('movieUser', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movieUser'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('channelConfig', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channelConfig'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('channelImg', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channelImg'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('sizeVideo', sa.Integer(), nullable=False),
    sa.Column('channelVideo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channelVideo'], ['channel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(length=50), nullable=False),
    sa.Column('videos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['videos'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('username', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('password_hash', sa.String(length=250), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'password')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'username')
    op.drop_table('categories')
    op.drop_table('videos')
    op.drop_table('source')
    op.drop_table('config')
    op.drop_table('movie')
    op.drop_table('messages')
    op.drop_table('img')
    op.drop_table('following')
    op.drop_table('channel')
    op.drop_table('banner')
    # ### end Alembic commands ###
